echo "l2_controllers[0-9]*.L2cache.m_demand_accesses"
echo "l2_controllers[0-9]*.L2cache.m_demand_hits"
echo "l2_controllers[0-9]*.L2cache.m_demand_misses"
echo "l1_controllers0.L1[A-Z]*cache.m_demand_accesses"
echo "l1_controllers0.L1[A-Z]*cache.m_demand_hits"
echo "l1_controllers0.L1[A-Z]*cache.m_demand_misses"
