qsub 1_deepsjeng_second.sh
qsub 1_exchange2_second.sh
qsub 1_gcc_second.sh
qsub 1_leela_second.sh
qsub 1_mcf_second.sh
qsub 1_omnet_second.sh
qsub 1_perl_second.sh
qsub 1_x264_second.sh
qsub 1_xalancbmk_second.sh
qsub 1_xz_second.sh
qsub 2_deepsjeng_second.sh
qsub 2_exchange2_second.sh
qsub 2_gcc_second.sh
qsub 2_leela_second.sh
qsub 2_mcf_second.sh
qsub 2_omnet_second.sh
qsub 2_perl_second.sh
qsub 2_x264_second.sh
qsub 2_xalancbmk_second.sh
qsub 2_xz_second.sh
qsub 4_deepsjeng_second.sh
qsub 4_exchange2_second.sh
qsub 4_gcc_second.sh
qsub 4_leela_second.sh
qsub 4_mcf_second.sh
qsub 4_omnet_second.sh
qsub 4_perl_second.sh
qsub 4_x264_second.sh
qsub 4_xalancbmk_second.sh
qsub 4_xz_second.sh
